### PR TITLE
Picker selected item text color feature

### PR DESCRIPTION
**Pull request by Jeadonara**
For a better UI, the selected picker item text color feature has been developed.

### CODE REVIEW

**Comment by GregFrench** [comment]
Does this work on iOS, or just Android?

**Comment by Jeadonara** [comment]
Only Android

**Comment by GregFrench** [comment]
Ok, I'm willing to merge this in and will state that the property Is Android only. Can you adjust the code so that the selected text color defaults to textColor if the selectedTextColor prop is missing?

**Comment by Eigilak** [comment]
The current version has issues regarding IOS 15. For some reason a float or a int cant be passed as value in picker.item. It gives an instant crash. 

Issue is both on the attribute:                   selectedValue={parseInt(pickerValue) % 10} and in the picker.item value

No issues on IOS 14.5 and below

**Comment by MohammadAzimi** [comment]
Hey @GregFrench,  I want to create an issue on this repo. but I don't find the issue tab! and any other links to connect you

**Comment by GregFrench** [comment]
Hi Mohammad, sorry about that. The issues tab was toggled off in the settings for some reason. Try it now.

**Comment by GregFrench** [comment]
> The current version has issues regarding IOS 15. For some reason a float or a int cant be passed as value in picker.item. It gives an instant crash.
> 
> Issue is both on the attribute: selectedValue={parseInt(pickerValue) % 10} and in the picker.item value
> 
> No issues on IOS 14.5 and below

Could you send a PR in for a fix and I'll take a look? Thanks

**Pull request closed without merging**
